[package]
name = "wooting-integrations"
version = "0.1.1"
authors = ["Shayne Hartford <shaybox@shaybox.com>"]
edition = "2021"
description = "My personal Wooting keyboard integrations"
readme = "README.md"
repository = "https://github.com/ShayBox/Wooting-Integrations"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
colorgrad = "0.6"
hidapi = "2"
hyprland = "0.4.0-alpha.2"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
